name: Nodejs application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "S@n101298" | docker login -u "san26" --password-stdin
        docker image build -t san26/conversao-temperatura:v1 .
        docker push san26/conversao-temperatura:v1
